config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :statuses
  resources :tickets
  resources :users do
    resources :tickets
  end
  resources :comments
  resources :replies
  resources :ticket_follows

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  root 'welcome#home'

  get 'auth/:provider/callback', to: 'sessions#oauth'

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController

  def show
    @status = Status.find_by(:id => params[:id])
    if @status
      @tickets = Ticket.where(:status_id => @status.id)
    else
      redirect_to root_path, :flash => {:alert => "Status does not exist."}
    end
  end

  def new
    @status = Status.new
  end

  def create
    @status = authorize Status.new(status_params)
    if @status.save
      redirect_to status_path(@status)
    else
      render :new #set a flash message
    end
  end

  def edit
    @status = Status.find_by(:id => params[:id])
    unless @status
      redirect_to root_path, :flash => {:alert => "Status does not exist."}
    end
  end

  def update
    @status = Status.find_by(:id => params[:id])
    if @status
      authorize @status
      if @status.update(status_params)
        redirect_to status_path(@status)
      else
        render :edit
      end
    else
      redirect_to root_path, :flash => {:alert => "Status does not exist."}
    end
  end

  private

    def status_params
      params.require(:status).permit(:name, :description)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= render partial: 'layouts/errors', locals: { object: @status } %>

<%= form_for @status do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br><br>
  <%= f.submit %>
<% end %>

app/views/statuses/edit.html.erb
<%= render partial: 'form' %>

app/views/statuses/new.html.erb
<%= render partial: 'layouts/errors', locals: { object: @status } %>

<%= form_for @status do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br><br>
  <%= f.submit %>
<% end %>

app/views/statuses/show.html.erb
<h1><%= @status.name %></h1>
<% if policy(@status).edit? %>
  <p><%= link_to "Edit status", edit_status_path(@status) %></p>
<% end %>
<p><%= @status.description %></p>

<%= render :partial => 'tickets/table', locals: { :tickets => @status.tickets } %>