config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :statuses
  resources :tickets
  resources :users do
    resources :tickets
  end
  resources :comments
  resources :replies
  resources :ticket_follows

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  root 'welcome#home'

  get 'auth/:provider/callback', to: 'sessions#oauth'

end

app/models/ticket.rb
class Ticket < ApplicationRecord

  scope :due_this_week, -> { where('due_date <= ?', Time.now + 1.week) }
  scope :past_due, -> { where('due_date <= ?', Time.now) }

  belongs_to :assignee, :class_name => "User", :foreign_key => "assignee_id"
  belongs_to :creator, :class_name => "User", :foreign_key => "creator_id"

  has_many :comments
  belongs_to :status

  has_many :ticket_follows
  has_many :followers, through: :ticket_follows, source: :user

  validates :title, presence: true
  validates :title, uniqueness: true
  validates :description, presence: true
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    unless @user = User.find_by(:id => params[:user_id])
      @tickets = Ticket.all
    end
  end

  def show
    @ticket = Ticket.find_by(:id => params[:id])
    if @ticket
      session[:ticket_id] = @ticket.id
      @comments = @ticket.comments
      @comment = Comment.new
      @reply = Reply.new
    else
      redirect_to root_path, :flash => {:alert => "Ticket does not exist."}
    end
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.new(ticket_params)
    if @ticket.save
      session[:ticket_id] = @ticket.id
      redirect_to ticket_path(@ticket)
    else
      render :new # set a flash message
    end
  end

  def edit
    @ticket = Ticket.find_by(:id => params[:id])
    if @ticket
      authorize @ticket
      session[:ticket_id] = @ticket.id
    else
      redirect_to root_path, :flash => {:alert => "Ticket does not exist."}
    end
  end

  def update
    @ticket = Ticket.find_by(:id => params[:id])
    if @ticket
      authorize @ticket
      if @ticket.update(ticket_params)
        redirect_to ticket_path(@ticket)
      else
        render :edit
      end
    else
      redirect_to root_path, :flash => {:alert => "Ticket does not exist."}
    end
  end

  def destroy
    @ticket = Ticket.find_by(:id => params[:id])
    if @ticket
      authorize @ticket
      session[:ticket_id] = @ticket.id
      if @ticket.destroy
        redirect_to tickets_path, :flash => {:alert => "Ticket successfully deleted."}
      else
        redirect_to ticket_path(@ticket)
      end
    else
      redirect_to root_path, :flash => {:alert => "Ticket does not exist."}
    end
  end

  private

    def ticket_params
      params.require(:ticket).permit(:creator_id, :title, :description, :status_id, :assignee_id, :due_date)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper

  def display_date(date)
    date.strftime("%Y-%m-%d")
  end

end

app/views/tickets/_follow_options.html.erb
<% if ticket.followers.include?(current_user) %>
  <%= link_to 'Unfollow this ticket', TicketFollow.find_by(:user_id => current_user.id, :ticket_id => ticket.id), method: :delete %>
<% else %>
  <%= link_to 'Follow this ticket', TicketFollow.new, method: :create %>
<% end %>

app/views/tickets/_followers.html.erb
<% ticket.followers.each do |f| %>
  <%= link_to f.name, user_tickets_path(f) %>
<% end %>

app/views/tickets/_form.html.erb
<%= form_for @ticket do |f| %>
  <%= f.hidden_field :creator_id, :value => current_user.id %>
  <%= f.label :title %><br>
  <%= f.text_field :title %><br>
  <%= f.label :description %><br>
  <%= f.text_area :description %><br>
  <%= f.label :status_id %><br>
  <%= f.collection_select :status_id, Status.all, :id, :name %><br>
  <%= f.label :assignee_id %><br>
  <%= f.collection_select :assignee_id, User.all, :id, :name %><br>
  <%= f.label :due_date %><br>
  <%= f.date_field :due_date %><br><br>
  <%= f.submit %><br>
<% end %>

app/views/tickets/_table.html.erb
<table class="w3-table w3-striped w3-table-all">
  <tr>
    <th class="ticket-title">Title</th>
    <th>Status</th>
    <th>Creator</th>
    <th>Assignee</th>
    <th>Due Date</th>
    <%= render partial: 'ticket_follows/notifications_column_header' %>
  </tr>
  <% tickets.each do |t| %>
  <tr>
    <td class="ticket-title"><%= link_to t.title, ticket_path(t) %></td>
    <td><%= link_to t.status.name, status_path(t.status) %></td>
    <td><%= link_to t.creator.name, user_tickets_path(t.creator) %></td>
    <td><%= link_to t.assignee.name, user_tickets_path(t.assignee) %></td>
    <td><%= t.due_date %></td>
    <%= render partial: 'ticket_follows/notifications_column_row', locals: { ticket: t } %>
  </tr>
  <% end %>
</table>

app/views/tickets/edit.html.erb
<%= render partial: 'layouts/errors', locals: { object: @ticket } %>
<%= render partial: 'form' %>

app/views/tickets/index.html.erb
<% if current_page?(tickets_path) %>
  <%# /tickets path - this is the standard tickets index %>

  <h1>All tickets</h1>
  <%= render :partial => 'tickets/table', locals: { :tickets => @tickets.order(:due_date) } %>

<% else %>
  <%# /users/:id/tickets - this is the nested tickets index %>

  <h1><%= @user.name %>'s Tickets</h1>
  <h4>Assigned tickets:</h4>
  <%= render :partial => 'tickets/table', locals: { :tickets => @user.assigned_tickets.order(:due_date) } %>

  <h4>Created tickets:</h4>
  <%= render :partial => 'tickets/table', locals: { :tickets => @user.created_tickets.order(:due_date) } %>
<% end %>

app/views/tickets/new.html.erb
<%= render partial: 'layouts/errors', locals: { object: @ticket } %>
<%= render partial: 'form' %>

app/views/tickets/show.html.erb
<h1><%= @ticket.title %></h1>
<% if policy(@ticket).edit? %>
  <p>
    <%= link_to "Edit ticket", edit_ticket_path(@ticket) %>
    <% if policy(@ticket).destroy? %>
      <%= link_to "Delete ticket", ticket_path(@ticket), :method => "delete", data: {:confirm => "Are you sure you want to delete this ticket?" } %>
    <% end %>
  </p>
<% end %>

<div class="ticket-status">
  Status: <%= link_to @ticket.status.name, status_path(@ticket.status) %><br>
</div>

<div class="container clearfix">
  <section class="ticket-description">
    <b>Description</b><br>
    <%= simple_format(@ticket.description) %>
  </section>

  <section class="ticket-dates-and-people">
    <b>Details</b><br>
    Created by: <%= link_to @ticket.creator.name, user_tickets_path(@ticket.creator) %><br>
    Assigned to: <%= link_to @ticket.assignee.name, user_tickets_path(@ticket.assignee) %><br>
    Due date: <%= @ticket.due_date %><br>
    Created on: <%= display_date(@ticket.created_at) %><br>
    Updated on: <%= display_date(@ticket.updated_at) %><br>
    Followers: <%= render :partial => 'followers', locals: { :ticket => @ticket } %><br>
    <%= render :partial => 'follow_options', locals: { :ticket => @ticket } %>
  </section>

  <section class="ticket-comment-details clearfix">
    <b>Comments</b><br>
    <% @comments.each do |c| %>
      <div class="comment-reply">
        <div class="comment">
          <%= link_to c.user.name, user_path(c.user) %>: <%= c.content %>
        </div>

        <div class="replies">
          <% c.replies.each do |r| %>
          <div class="reply">
            <%= link_to r.user.name, user_path(r.user) %>: <%= r.content %>
          </div>
          <% end %>
        </div>

        <div class="new-reply">
          <%= form_for @reply do |f| %>
            <%= f.hidden_field :comment_id, :value => c.id %>
            <%= f.text_area :content %><br>
            <%= f.submit %>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="new-comment">
      <%= form_for @comment do |f| %>
        <%= f.hidden_field :ticket_id, :value => @ticket.id %>
        <%= f.text_area :content %><br>
        <%= f.submit %>
      <% end %>
    </div>
  </section>
</div>