config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :statuses
  resources :tickets
  resources :users do
    resources :tickets
  end
  resources :comments
  resources :replies
  resources :ticket_follows

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'signup', to: 'users#new'
  get 'logout', to: 'sessions#destroy'
  root 'welcome#home'

  get 'auth/:provider/callback', to: 'sessions#oauth'

end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <%= pluralize(object.errors.count, "error") %> prohibited this <%= object.class.name.downcase %> from being saved:
    <% object.errors.full_messages.each do |msg| %>
      <br><span><%= msg %></span>
    <% end %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="w3-bar w3-red w3-card w3-left-align w3-medium navbar">
  <a class="w3-bar-item w3-button w3-hide-medium w3-hide-large w3-right w3-padding-large w3-hover-white w3-large w3-red" href="javascript:void(0);" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
  <% if logged_in? %>
    <%= link_to "Home", tickets_path, :class => "#{navbar_highlight(tickets_path)}" %>
    <%= link_to "My Tickets", user_tickets_path(current_user), :class => "#{navbar_highlight(user_tickets_path(current_user))}" %>
    <%= link_to "Followed Tickets", ticket_follows_path, :class => "#{navbar_highlight(ticket_follows_path)}" %>
    <%= link_to "New Ticket", new_ticket_path, :class => "#{navbar_highlight(new_ticket_path)}" %>
    <%= link_to "New Status", new_status_path, :class => "#{navbar_highlight(new_status_path)}" if current_user.is_admin? %>
    <%= link_to "Users", users_path, :class => "#{navbar_highlight(users_path)}" %>
    <%= link_to "Log Out", logout_path, :class => "#{navbar_highlight(logout_path)}" %>
  <% else %>
    <%= link_to "Home", root_path, :class => "#{navbar_highlight(root_path)}" %>
    <%= link_to "Log In", login_path, :class => "#{navbar_highlight(login_path)}" %>
    <%= link_to "Sign Up", signup_path, :class => "#{navbar_highlight(signup_path)}" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Apmt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script>
    $(document).on('turbolinks:load', function(){
      $("div.comment").click(function(){
        $(this).parent().find(".new-reply").toggle("fast");
      });
    });
    </script>
  </head>

  <body>
    <header>
      <%= render partial: 'layouts/navbar' %>
    </header>
    <main>
      <% flash.each do |key, value| %>
        <div class="alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
    </main>
  </body>
</html>